# Generated by Django 2.0.10 on 2019-02-07 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=100)),
                ('estate', models.CharField(max_length=100)),
                ('street_number', models.CharField(max_length=100)),
                ('house_number', models.CharField(max_length=100)),
                ('type_of_stay', models.CharField(choices=[('R', 'Rented'), ('O', 'Owner')], max_length=1)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed'), ('O', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'addresses',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'banks',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'branches',
            },
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer', models.CharField(max_length=200)),
                ('physical_address', models.CharField(max_length=200)),
                ('postal_address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=200)),
                ('staff_number', models.CharField(max_length=100)),
                ('employment_terms', models.CharField(choices=[('P', 'Parmanent'), ('C', 'Casual'), ('TR', 'Contract'), ('O', 'Other')], max_length=200)),
                ('bussiness_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rental_income', models.DecimalField(decimal_places=2, max_digits=15)),
                ('other_incomes', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'employments',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.PositiveSmallIntegerField(choices=[(0, 'Normal Loan'), (1, 'development Loan'), (2, 'Emergency Loan')])),
                ('amount_requested', models.DecimalField(decimal_places=4, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'loans',
            },
        ),
        migrations.CreateModel(
            name='Other_Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=200)),
                ('amount_advanced', models.DecimalField(decimal_places=4, max_digits=12)),
                ('outstanding_balance', models.DecimalField(decimal_places=4, max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'other_loans',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membership_number', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=100)),
                ('home_address', models.CharField(max_length=100)),
                ('office_phone', models.CharField(max_length=100)),
                ('mobile_phone', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles',
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='User_Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Bank')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Branch')),
            ],
            options={
                'db_table': 'user_banks',
            },
        ),
        migrations.AddField(
            model_name='other_loan',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Profile'),
        ),
        migrations.AddField(
            model_name='loan',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Profile'),
        ),
        migrations.AddField(
            model_name='employment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Profile'),
        ),
        migrations.AddField(
            model_name='address',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.Profile'),
        ),
    ]
